package day25_consrctur;

public class C01 {
    //JAVA OOP KONSET KULLANDIGI ICIN OLUSTURULAN HER BIR CLASIN
    //IHTIYAC OLDUGUNDA OBJE URETEBILMESINE UYGUN DIZATN ETMISTIR
    //AMA HER CLASDAN OBJE URETILMEYEBILIR

    //BUNUN ICIN JAVA IHTIYAC HALINDE HER CLASDA DEFAULT CONSRACTUR KOYMUSTUR VE
    //OBJE OLUSTURULMADIGINDA DEFAULT CONSRUCTUR OTOMATIK OLARAK CALISR
    int sayi;
    //metod olusturalim

    public void deneme(){
        System.out.println("C01 den deneme metodu");
    }
}
